name: Test
on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        emacs_version:
        # - 25.1
        # - 25.2
        # - 25.3
        # - 26.1
        # - 26.2
        - 26.3
        # - snapshot
    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - uses: conao3/setup-cask@master
    - uses: actions/checkout@v2
    - name: Test
      run: |
        # Install Emacs (according to $EMACS_VERSION) and Cask
        make -f emacs-travis.mk install_emacs
        make -f emacs-travis.mk install_cask
        emacs --version
        # Install dependencies
        cask install
        # Run tests and upload coverage
        COVERALLS_PARALLEL=1 make test
